/* B2 Labz — content data */
window.BBZ_DATA = {
  services: [
    {
      cls: 'Class 01',
      name: 'Starter',
      tag: 'One-Pager',
      desc: 'A single, focused page that introduces your offer and pushes one clear action.',
      price: '$650',
      timeline: '2–5 Days',
      featured: false,
      bullets: [
        'One-page premium layout',
        'Mobile-first responsive',
        'Hero + about + services + contact',
        'Vercel deployment + preview link',
        'Basic copy cleanup',
      ],
    },
    {
      cls: 'Class 02',
      name: 'Business',
      tag: 'Service Sites',
      desc: 'A complete site for local service providers — pages, booking link, basic SEO, full handoff.',
      price: '$1,400',
      timeline: '5–10 Days',
      featured: true,
      bullets: [
        'Home, About, Services, Contact, FAQ',
        'Booking link or contact form',
        'Gallery / testimonials section',
        'Basic SEO setup + sitemap',
        'GitHub repo + Vercel deployment',
      ],
    },
    {
      cls: 'Class 03',
      name: 'Premium Brand',
      tag: 'Flagship',
      desc: 'Our highest tier — Godly-inspired layouts, motion, custom sections, strategic copy.',
      price: '$3,200',
      timeline: '10–21 Days',
      featured: false,
      bullets: [
        'Bespoke premium layout',
        'Animations + motion effects',
        'Portfolio / case study system',
        'Lead capture + conversion strategy',
        'Launch checklist + handoff doc',
      ],
    },
    {
      cls: 'Class 04',
      name: 'Creator',
      tag: 'Portfolio',
      desc: 'Show who you are, what you make, and how to book you — in one cinematic scroll.',
      price: '$900',
      timeline: '3–7 Days',
      featured: false,
      bullets: [
        'Personal bio + featured work',
        'Portfolio / gallery grid',
        'Media embeds (audio, video)',
        'Social hub + contact CTA',
        'Mobile-first launch',
      ],
    },
    {
      cls: 'Class 05',
      name: 'E-Commerce Lite',
      tag: 'Sellers',
      desc: 'A focused product showcase with payment links — no complicated store to manage.',
      price: '$1,800',
      timeline: '7–14 Days',
      featured: false,
      bullets: [
        'Product showcase cards',
        'Brand story + drop page',
        'Stripe / payment link buttons',
        'FAQ + contact + basic SEO',
        'Mobile-first checkout flow',
      ],
    },
    {
      cls: 'Class 06',
      name: 'Care Plan',
      tag: 'Recurring',
      desc: 'We keep your site fresh — text, images, links, performance — so you never go stale.',
      price: '$120 / mo',
      timeline: 'Ongoing',
      featured: false,
      bullets: [
        'Monthly text + image edits',
        'Link + performance checks',
        'Monthly improvement suggestions',
        'Priority response window',
        'Pause / cancel anytime',
      ],
    },
  ],

  process: [
    { n: '01', title: 'Intake',            out: 'Project Brief',  desc: 'We collect your business details, goals, photos, links, and the style direction you’re after.' },
    { n: '02', title: 'Strategy',          out: 'Page Plan',      desc: 'We decide what the site must do — bookings, calls, sales, trust — and map the page structure.' },
    { n: '03', title: 'Direction',         out: 'Mood Board',     desc: 'Curated references from Godly, 21st.dev, and our own archive shape a custom visual direction unique to your brand.' },
    { n: '04', title: 'Build',             out: 'Live Preview',   desc: 'We plan the structure and copy, build the components, and you see progress in real time on a preview link.' },
    { n: '05', title: 'Review',            out: 'Revision List',  desc: 'You get a preview link with structured feedback prompts. One organized round, no death-by-tweak.' },
    { n: '06', title: 'Launch',            out: 'Live Website',   desc: 'Domain connected, performance checked, mobile tested, GitHub committed, Vercel live. Done.' },
  ],

  work: [
    { name: 'Lumen Barbershop',  cat: 'Local Service · Class 02',  span: 4, ratio: 'wide',  num: '01',
      img: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=1200&q=80&auto=format&fit=crop',
      bg: 'radial-gradient(ellipse 80% 100% at 50% 100%, #14B8A6 0%, #0A3656 45%, #02060E 100%)' },
    { name: 'Ines Couture',      cat: 'Fashion · Class 03',        span: 2, ratio: 'tall',  num: '02',
      img: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1000&q=80&auto=format&fit=crop',
      bg: 'radial-gradient(ellipse 70% 90% at 70% 30%, #58D6FF 0%, #0A3656 50%, #02060E 100%)' },
    { name: 'Ola Studio',        cat: 'Creator · Class 04',        span: 2, ratio: 'tall',  num: '03',
      img: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=1000&q=80&auto=format&fit=crop',
      bg: 'radial-gradient(ellipse 100% 60% at 50% 50%, #2EE6D0 0%, #115E78 40%, #02060E 100%)' },
    { name: 'Reef + Co.',        cat: 'E-Commerce · Class 05',     span: 2, ratio: 'tall',  num: '04',
      img: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1000&q=80&auto=format&fit=crop',
      bg: 'radial-gradient(ellipse 80% 70% at 30% 70%, #7CF5DC 0%, #0A3656 50%, #02060E 100%)' },
    { name: 'Atlas Trainers',    cat: 'Coach · Class 02',          span: 2, ratio: 'tall',  num: '05',
      img: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1000&q=80&auto=format&fit=crop',
      bg: 'radial-gradient(ellipse 60% 80% at 60% 40%, #58D6FF 0%, #072541 55%, #02060E 100%)' },
    { name: 'Verdant Catering',  cat: 'Food · Class 02',           span: 4, ratio: 'wide',  num: '06',
      img: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200&q=80&auto=format&fit=crop',
      bg: 'radial-gradient(ellipse 90% 60% at 30% 30%, #14E1A8 0%, #0A3656 50%, #02060E 100%)' },
  ],

  whyItems: [
    { ix: '01', title: 'Built For Speed',          body: 'A modern workflow and a sharp toolkit — your site launches in days, not months.' },
    { ix: '02', title: 'Premium Visual Direction', body: 'Inspired by Godly + 21st.dev. We refuse to ship template-looking sites.' },
    { ix: '03', title: 'Beginner-Friendly',        body: 'No tech jargon. We guide you through every step in plain language.' },
    { ix: '04', title: 'Fixed Packages',           body: 'Clear scope. Clear timeline. Clear price. No surprise invoices.' },
    { ix: '05', title: 'Modern Tech Stack',        body: 'GitHub for code, Vercel for hosting. You own everything we build.' },
    { ix: '06', title: 'Done-For-You',             body: 'Strategy, copy, design, build, launch. You bring the business. We do the rest.' },
  ],

  faq: [
    { q: 'I have no website, no copy, and barely any photos. Can you still help?',
      a: 'Yes — that\'s the most common starting point. Our intake form walks you through everything we need, and our Copywriting Upgrade fills the gap if you don\'t know what to say. You bring the business, we shape the presence.' },
    { q: 'How long does a typical build take?',
      a: 'A Starter goes live in 2–5 days. Business sites take 5–10 days. Premium Brand builds run 10–21 days depending on scope. Rush delivery is available as an add-on.' },
    { q: 'Do I own the website after launch?',
      a: 'Completely. Code lives in a GitHub repo we hand off to you. Hosting on Vercel is in your name. Domain stays yours. No platform lock-in, no monthly fee unless you opt into a Care Plan.' },
    { q: 'What if I don\'t like the first preview?',
      a: 'One organized round of revisions is built into every package. Each class has a scope — we\'ll tweak within it freely, and anything outside scope becomes an add-on so the project doesn\'t balloon. Most clients approve the second preview.' },
    { q: 'Do you handle ongoing updates after launch?',
      a: 'Through the Care Plan. $120/month covers small edits, image swaps, link updates, performance checks, and monthly suggestions. Otherwise, we hand off the repo and you\'re free to update it yourself or hire anyone.' },
    { q: 'Can you build me a Shopify / WordPress / Wix site?',
      a: 'We build custom, hand-crafted sites — not template platforms. The result loads faster, looks better, and isn\'t locked into a subscription. For most small businesses and creators, this is the better long-term move.' },
  ],

  stats: [
    { num: '5+',  lbl: 'Years In The Lab' },
    { num: '50+', lbl: 'Sites Shipped' },
    { num: '99%', lbl: 'Mobile-Ready' },
    { num: '7d',  lbl: 'Avg. To Launch' },
  ],
};
